= eselling

A Java desktop app for maintaining a list of items for sale, and exporting them to various markets
such as eBay, Kijiji, etc.
The eBay and FB markets output a file that can be uploaded via the web.
Kijiji refuses to provide an API or even an upload, so we try to
insert the item using Selenium Web Driver.

The model code and the per-market export code is from my previous human-coded eselling web app.
The Swing UI was written by Claude AI and heavily modified afterwards.
The WebDriver code was written by one of the common AIs, I forget which.

== HowTo Use

You'll need at least a permanent database (PostgreSQL recommended). To hook that up,
In `src/main/resources/META-INF`, copy the sample file to `persistence.xml`, and modify
it to suit.

Once that's in place you might be able to run it with `gradle run`

To package it, 'gradle jar' which will create build/libs/eselling-admin-?.?-SNAPSHOT.jar

For safekeeping, you should copy that file to someplace more generic, like `~/lib`

You can then run `java -jar ~/lib/eselling*.jar` to try it out.
Assuming it works, create a one-line shell script, shell alias or `.bat` file to run it.

== ToDo

Repair use of template method to reduce duplication in list() calls in Market.
