= eSelling Project

This Vaadin-Quarkus-based project tracks personal items that I am trying to sell.

It began life as a collision between a Gemini-built main View
and the canonical Vaadin/Quarkus starter app.

There is no main() method; run using `mvn` or `mvn quarkus:dev`

Then open http://localhost:8080/[] in browser.

To run locally in production mode, call `mvn package -Pproduction` 
and then
`java -jar target/quarkus-app/quarkus-run.jar`

== Database

You need to create a file called .env (which is gitignored) in the root,
containing the properties needed in the application.properties.

The current version is set up for PostgreSQL.  If you use a different db,
you'll have to change the module in the pom file, and in the application.properties.

To create the database tables, run the commands in sql/setup.sql

To create a user manually:

	echo -n 'mysecretpassword1234' | md5 # or md5sum
	psql
		insert into Users(id, username, passwordhash) values(0, 'username', '<result-of-hash>');
		^D

== TODO

Clean up error handling

Add fields:
	Category?
	Condition qualification
	Quantity
	Photos!?

=== Longer-term:

	Add ability to list items from the app's data out to eBay, Amazon, Kijiji, etc. via REST.

