#!/bin/sh

USAGE="Usage: ${0##*/} [-c]"

function usage {		# give usage message, and exit
	echo "Usage: ${USAGE}" 2>&1
	exit 1
}

CLEAN=""

while getopts "c" opt
do
	case "$opt" in
		c)	CLEAN="rm -r build";;
		*)	usage;;
	esac
done
shift `expr $OPTIND - 1`		 # leave just filenames

set -x
$CLEAN
withjava 21 gradle run
